### ISSUE TITLE
Docs haven't been built for more than a year

### ISSUE THREAD

**Issue by edmcdonagh** [jurismarches/luqum#46]
Install instruction refers to cookiecutter, and comes from here: d0bf7d78a29eee0cbfc324

**Comment by edmcdonagh** [comment]
https://luqum.readthedocs.io/en/latest/install.html

**Comment by alexgarel** [comment]
Wow good catch. Thanks !

I had to launch a build by clicking in readthedocs. (Also I remove/recreate the tags, because they where not seen by readthedocs). I though it was automatic ! I connected my account to readthedocs, hope it will help !

I have also added a config file to see if this can helps.
