### ISSUE TITLE
Publish a new release of luqum

### ISSUE THREAD

**Issue by alexgarel** [jurismarches/luqum#84]
As there was a lot of changes, it's interesting to do a new release

There is a target for that in the makefile, but you should first:
- update CHANGELOG.rst (sorry I forgot to do that in my PRs) by looking at PRs merged since last release
- change version number

@mmoriniere do you want to do it ? I may also do it, I just make me owner of packages :-D

**Comment by mmoriniere** [comment]
@alexgarel Yes, I wanted to do a 0.12.0 release (and duly noted some updates to the Changelog were needed, as well as a version bump) but I have other priorities at the moment.

You may do it yourself, now that you granted you the right to do so. Otherwise, I would be glad to do it in a couple of days.

**Comment by mmoriniere** [comment]
@alexgarel You may want to check everything is alright before I merge and make a new release on PyPI.
