### ISSUE TITLE
Support implicit OR operation 

### ISSUE THREAD

**Issue by erlichmen** [jurismarches/luqum#9]
The following should be a valid lucene syntax:
```
name:bob city:nyc
```
it should equivalent to:
```
name:bob OR city:nyc
```
But I get UnknowOperation instead of OrOperation when parsing the string.

**Comment by alexgarel** [comment]
hello, sorry I'm on vacation, mainly AFK. 

As a first short answer, the choice of OR or AND as the implicit operator is a choice than can be made later (see eg the default_operator argument in [Query String Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) and in `luqum.elasticsearch.visitor.ElasticsearchQueryBuilder.__init__`). 

That's why the parser prefers to use this specific `UnknowOperation` node. 

So you can either decide to use a visitor to replace the `UnknownOperation` to a `OrOperation` or treat `UnknownOperation` as a `OrOperation` in your code. 

Hope it's clear enough !

**Comment by alexgarel** [comment]
Hello @erlichmen, can you get a look at https://github.com/jurismarches/luqum/pull/12 and tell me if this solutions seems ok to you.

**Comment by alexgarel** [comment]
@erlichmen did you look into it ? Without any response within two weeks I'll close this ticket. Thanks.

**Comment by erlichmen** [comment]
@alexgarel Works for me!.

**Comment by impredicative** [comment]
For any reader who is wondering how to use it:

```python
from luqum.parser import parser
from luqum.utils import UnknownOperationResolver
from luqum.tree import AndOperation


unk_op_resolver = UnknownOperationResolver(AndOperation)
tree = unk_op_resolver(parser.parse('foo bar'))
```

**Comment by alexgarel** [comment]
good idea to put the code here @impredicative. There is also [a reference in the doc](https://luqum.readthedocs.io/en/latest/quick_start.html#the-unknown-operation)
